Confdir = "./conf.d"
Db = "./diff.db"

[Queues.debug]
	User = "rootdev.robot@gmail.com"
	Pass = "ZXK3u7NK72PEAZfEA"
	Host = "smtp.gmail.com"
	Port = 465
	From = "rootdev.robot@gmail.com"
	FromName="DeltaReport"
	To = ["rootdev@gmail.com"]
	Support = "rootdev@gmail.com"
	Subject= "[AUTOGEN] "

[[Files]]
	# Queue to newline/sess about any changes in subfiles and separate by newline
	Path = "./test.d"
	To = "debug"
	Recurse = true
	IncludeExt = [
		".txt",
		".log"
	]
	#Regex = "/valid.txt$"
